### ISSUE TITLE
Feature: copy/pull account data from a live environment

### ISSUE THREAD

**Issue by wjthieme** [kevinheavey/solana-bankrun#4]
Should be relatively easy to implement. Might have a go at it later.

* Supply a list of accounts to copy in `start` and the rpc url to copy from.
* Get their account data from the environment.
* Initialize them as `AddedAccounts`

Anything I am missing here?

**Comment by kevinheavey** [comment]
I agree that this should be relatively easy to implement, but I'm inclined to think it's out of scope because it's not something that Bankrun is well-suited to help with. My thinking is that adding arbitrary account data is Bankrun's job. Generating or fetching that data is not.

We could certainly add an example to the docs showing how to do this though

**Comment by wjthieme** [comment]
Sounds good! Will create a PR for that
